// TODO: Add and export actions: ADD_BOOK, REMOVE_BOOK, SEARCH_BOOKS

const ADD_BOOK = 'ADD_BOOK'
const REMOVE_BOOK = 'REMOVE_BOOK'
const SEARCH_BOOKS = 'SEARCH_BOOKS'

export {ADD_BOOK, SEARCH_BOOKS, REMOVE_BOOK}